find_package(Boost 1.76 CONFIG QUIET)
if(NOT Boost_FOUND)
  CPMAddPackage(NAME boost_mp11 VERSION 1.78 GITHUB_REPOSITORY "boostorg/mp11")
  set(BOOST_MP11_TARGET Boost::mp11)
else()
  set(BOOST_MP11_TARGET Boost::boost)
endif()

find_package(doctest 2.4.7 CONFIG QUIET)
if(NOT doctest_FOUND AND ML_MOVAR_BUILD_TEST)
  CPMAddPackage(doctest VERSION 2.4.7 GITHUB_REPOSITORY doctest/doctest)
endif()

if (ML_MOVAR_BUILD_DOCUMENTATION)
  find_package(Doxygen 1.9.3 REQUIRED)
  CPMAddPackage(NAME doxygen-awesome-css VERSION 2.0.3 GITHUB_REPOSITORY jothepro/doxygen-awesome-css)
  CPMAddPackage(NAME mcss GITHUB_REPOSITORY mosra/m.css GIT_TAG master)
endif()